### ISSUE TITLE
Main page: difference among buttons not evident

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#10]
Vittoriano: "Clean and simple, the main page is as we asked, but in terms of usability there is still the problem that three button work with urls and the other two requests a different input - and this is not self-evident. With use and habit this ‘difference’ can disappear but it could still be a problem for first time and infrequent users. I propose to use longer sentences with a stronger font within the search box (like Google does) and different button colors for the last two. I suppose we will use cookies on the web site, so for the first time user could useful to have the first time all the mouseover exploded, so to make the choice simpler."

**Comment by dcabo** [comment]
@danielevannella Daniele, I'm going to start entering the user feedback as issues here, as agreed in the last Rome meeting. I'm going to try to label them so they are easier to manage. Should I assign all the LiveTech ones to you, or is the front-end developer in Github also?

**Comment by macagari** [comment]
> @danielevannella Daniele, I'm going to start entering the user feedback as issues here, as agreed in the last Rome meeting. I'm going to try to label them so they are easier to manage. Should I assign all the LiveTech ones to you, or is the front-end developer in Github also?
@dcabo  I don't know why I can be assigned to any issue tracker, I will ask why to Claudia Zandoli.
Can you tag me in the new issues about the UI? Thank you in advance.
