### ISSUE TITLE
Relevance score for text

### ISSUE THREAD

**Issue by jdgryse** [fandangOrg/fandango#103]
Concerning this article: https://www.reuters.com/article/uk-factcheck-masks-idUSKBN29X2S5

The text relevance score is problematically low. 
The formula for the text relevance score is the following: IF( word_count > 400, 1, modulus( word_count / 400, 1 ) ).
This article has more than 400 words, so the relevance score should be 100%, which is not the case (somewhere around 5% or so).
So either the formula is not correctly implemented, or the text on which the score is being computed is not correct.
<img width="1172" alt="Screenshot 2021-02-04 at 10 46 37" src="https://user-images.githubusercontent.com/7630326/106874776-431de800-66d6-11eb-9f7d-c1d8e4e85021.png">

**Comment by mmagaldi-eng** [comment]
I've checked into ES: body is > 470 words, so @pstalidis should revise the formula implementation.

**Comment by pstalidis** [comment]
I am not calculating the relevance score, I am using whatever is provided by the analysers.
the text relevance score should be checked by @macagari

**Comment by macagari** [comment]
I checked that, there was an issue in the code, I'll update today the new image so you can let me know if it is working better

**Comment by macagari** [comment]
@jdgryse I took a look and I was calling an old module, now it is correct. I'll update it today or next Monday. Thank you!
