### ISSUE TITLE
Error on Fandango Link to Dashboard 

### ISSUE THREAD

**Issue by vittorianovancini** [fandangOrg/fandango#106]
![Dashboard Latest suspicious news](https://user-images.githubusercontent.com/37619775/107980809-2ed4c780-6fc1-11eb-8e40-916d2d511a10.png)

Clicking on Latest Suspicious News lands here, with three error message as you can see. However, the Dashboard works well if you access it outside this link.

**Comment by macagari** [comment]
Siren sent the correct link, I will update the image today with this and TNT new link
