### ISSUE TITLE
Video still very slow 

### ISSUE THREAD

**Issue by vittorianovancini** [fandangOrg/fandango#107]
[6secondsvideoFandango.pdf](https://github.com/fandangOrg/fandango/files/5983383/6secondsvideoFandango.pdf)

![7secondsVideo](https://user-images.githubusercontent.com/37619775/107981509-7f005980-6fc2-11eb-9d4f-b1c2aea90d17.png)

The tool executed the analysis of this (https://www.youtube.com/watch?v=28xCVQLvL0Y) 6 seconds video in 7 minutes, but this is not the big problem. This other video of 9 seconds (https://www.youtube.com/watch?v=wvWK0HF9C04) was not analyzed and I closed the tool after 50 minutes.

**Comment by vittorianovancini** [comment]
Since it is so difficult to find fake video (because those are very quickly deleted, when discovered by fact-checkers), maybe we could prepare a fake fake video, sort of prof of concept - and a very short one. What do you think? I'll try something in the next days...

**Comment by vittorianovancini** [comment]
I've created this very short video (less than 4 seconds) and uploaded on Youtube to be able to analyze it with Fandango

https://www.youtube.com/watch?v=ieQoLWfXr3U

but after 40 minutes, still no answer. I think that now we can say that there is some problem with the tool

**Comment by macagari** [comment]
I'll check form the UI side

**Comment by mmagaldi-eng** [comment]
@pstalidis, please check what's the problem, since it seems that it's slower than in the past. 
Once you've solved all software issues (don't forget the handling of multiple requests from UI issue), then we'll add more resources to speed up video analysis.

**Comment by pstalidis** [comment]
@mmagaldi-eng you remember when the module was running from a different server
handling of multiple requests is solved in #102.
Speeding up will happen when it is deployed in GPUs 

Closing this issue and we will track the speed after GPU integration in issue #112.
