### ISSUE TITLE
Fandango Claims not showing Url and Label content

### ISSUE THREAD

**Issue by vittorianovancini** [fandangOrg/fandango#108]
![image](https://user-images.githubusercontent.com/37619775/108399181-24f9d100-721a-11eb-9674-32cdcb25f601.png)

With the Claim-reviews just ingested off-line the "Label" (which should correspond to the "reviewRating.alternateName") and the URL in the external arrow icon are empty, while on the Dashboard they appear to be regularly populated.  Also, the text pop-up appears only when the claim record is closed.

![image](https://user-images.githubusercontent.com/37619775/108399945-f92b1b00-721a-11eb-9043-e4a6ae9ed8c7.png)

And the text could be wider, to help the reader...

**Comment by macagari** [comment]
We didn't change anything in the services, so if it was there before it should be there if the output object of the services is correct. I can change the text pop-up next time I update the image.

**Comment by vittorianovancini** [comment]
Thanks for the Text!
![image](https://user-images.githubusercontent.com/37619775/108701966-ecebda00-7508-11eb-9aaf-3c9c3887ddbc.png)
As you can see, "URL" and "Label" value are in the TABLE/JSON...
![image](https://user-images.githubusercontent.com/37619775/108702890-28d36f00-750a-11eb-95fa-7c2b979383e3.png)
This is a claim ingested last year, and Fandango fetches correctly the URL and the "reviewRating_alternateName"...

**Comment by macagari** [comment]
Yes, but the problem is the output of the service, Neil told that he is working on them so tomorrow I can check if they are ready. I added what you suggested for the text of the claims.
