### ISSUE TITLE
Elastic warning message:  Couldn't find mappings for field "articleBody" in index pattern "fdg-article"

### ISSUE THREAD

**Issue by mmagaldi-eng** [fandangOrg/fandango#113]
@neilpbyrne, please check what's wrong here.
![image](https://user-images.githubusercontent.com/37866168/109182719-888d7c80-778d-11eb-8a4c-a452eaf70dda.png)

**Comment by neilpbyrne** [comment]
Hi @mmagaldi-eng I can't replicate the issue. The dashboard loads fine for me. Is it still the same for you if you refresh your browser?

**Comment by mmagaldi-eng** [comment]
No. thanks.
