### ISSUE TITLE
Dashboard interface adjustments needed

### ISSUE THREAD

**Issue by vittorianovancini** [fandangOrg/fandango#115]
Dear Jeferson and Neil, In order to show the Dashboard during the Pilot and the Final Review, here are some adjustment about the name of some of the Dashboards Panels and some other issues the end users (not only me...) encountered during the check. Please remember that we plan to show the dashboard during the Pilot next week. Best. Vittoriano
Dashboard Analysis
PAGE BY PAGE INTERFACE ADJUSTMENTS

Latest Suspicious News (Fandango’s label) or Latest News Dashboard
(We can change either name, but I think they should have the same name…)

 

PANELS:
1)    Article Details Sorted by Calculated Rating, Descending PANEL

-       better: “Articles Details Sorted by Trustworthiness”

-       There is also a “Topic” issue, see the Article Topics…

 

2)     Article’s Tweets

-       better: “Latest Tweets on possible fake news topics”

-       The tweets ingestion should be reactivated, and we should be sure that the hashtags we gave David work properly. Please arrange for a test run this week if possible.

 

3)    Article Topics

-       This does not work well, regarding the topic field (searching Covid with “work” is not logic or desirable). Instead, use data from the keywords field? Is it possible? (Please extend this change to all the similar panels in other Dashboard pages)

-       Clicking on a topic should have related results in all the other panels (or at least Articles, Tweets and Claims) of the page, otherwise this panel has a limited usefulness

 

4)    Calculated Rating Distribution and # of Articles with Score lower than 20 – possible fake news should be moved below Article Topics

 

5)    Article’s Author

-       better: “Latest Articles by Author”. This is supposed to be a selection of the last two weeks articles ingested by Fandango, sorted by Author trustworthiness.

-       the URL does not work

-       Status has no meaning for the user, should be removed

 

6)    Publisher Search Result

-       better: “Latest Articles by Publisher”. This is supposed to be a selection of the articles from the last two weeks, ingested by Fandango and sorted by Publisher trustworthiness

-       Country is not working very well…

-       Nationality, same as above

-       Relevance: compared to what?

-       Status has no meaning for the user, should be removed

-       Name is almost always without spaces, not very readable

 

7)    Claims

-       Rating is 0 for 455 claims (we can translate the label value into a figure – we can give you a table reference if you need it)

-       Claim: about 10,000 claims have the Claim/Text field empty

-       Source is also empty (what value should be there?)

But it gets more worrisome if you analyze the Table/Json fields:

-       Author.name is almost never matches the name of the Author and should be corrected or removed (or at least not taken into account)

-       Author.sameAs is usually an URL of YouTube video or similar, often no longer available. Of course, this is an error, and the field should be corrected or removed

-       dateCreated and dateModified do not have any real value for the common user

-       What matters most is the datePublished and every sorting by date in the Dashboard should refer to this value not to the others.

-       mentions contains hexadecimal values. Why?

 

8)    Claim Reviews

Since this panel contains all the elements of the Claim panel and more, I think we could remove that one and only leave this one in the Dashboard pages.

 

-       Reviewer

-       better if this was instead the “reviewRating.alternateName” value and its name was changed in Reviewer Rating

-       Link of Review is empty in a lot of the last ingested claim and there is only the root url in the others. Please use instead the “url” value.

 

Tweet 360°
 

1)    Search Results from Tweets

The search results should be related in the other panels of the page. If you search “Brexit”, for example, only the Tweets panel show an answer.

-       The field under the Twitter’s Author is empty and can be removed

-       Text cannot be used as Filter for Value

 

2)    Articles

-       This selection (there are only 4,428 articles in this list now) should be more evidently related to the Tweets list.

-       datePublished should be the one used, here and everywhere

 

3)    Claim Count

-       This could be interesting for statistical purposes, but there is no other use for it. If you click on the claim it does not change anything in the other panels, because there is no correlation of values. Any suggestion?

 

4)    Claim Review Body

better: “Related Claim Reviews”. Of course, in this panel there should be related claims

…and, again as above:

-       Reviewer: better if this was instead the “reviewRating.alternateName” value and its name was changed in Reviewer Rating

-       Link of Review is empty in a lot of the last ingested claim and there is only the root url in the others. Please use instead the “url” value.

 

 

Article 360°
Minor adjustments needed:

 

1)    Articles details

-       DataCreated should be DataPublished

-       Calculated Rating: which one is this? Should be Overall Score

-       Source Domain: in this case it could be called “Publisher Domain”, so we can use it to search the Publisher related articles…

-       Topic: not useful at all (it should refer to the keywords if possible)

 

2)    Article Tweets

Are we sure they are related to the Article searched? (or the best next thing…)

 

3)    Article 360 Text

These are the keywords. So, let’s call it “Article 360 Keywords”

 

4)    Article’s Author

-       Maybe Author’s Articles reflects better what is supposed to show this panel…

-       the URL does not work

-       Status has no meaning for the user, should be removed

 

5)    Article Publisher

-       It should contain Publisher related to the search, but there are no details apart from the Trustworthiness, which already is in the “Publisher’s Trustworthiness from 0 to 100”. Country and Nationality could also be redundant. Can we find other interesting elements or we just remove it?

 

Author 360°
I’ve tried the Dashboard from Fandango Author shortcut - with a name different from Anonymous - and the result quite good. Some adjustment is still needed, though.

 

1)    Author’s Articles

-       If the “Topic” field does not contain significant data, it’s better removed

-       “Author’s Article Graph Browser” is too heavy, even when 100 nodes only mode is selected. And this happened with an Author who had only an article inside Fandango. So, maybe there is something out of sync here…

 

Publisher 360°
 

1)    “Publisher by Author” panel is empty: what is supposed to appear here?  If you can’t find (in the system) significant data to show, I think it should be better removed…

 

2)    “Article’s Tweets”: it should be related to the Publisher’s Twitter account, with its latest tweets.

 

3)    Maybe we could add “Related Dashboards”, “Top 30 by Bias” and “Publisher by Parent Organization”… what do you think?

**Comment by jefersonzanim** [comment]
@vittorianovancini we'll look into those. Bear in mind that it isn't always possible to achieve some of those without the data being updated.

**Comment by mmagaldi-eng** [comment]
@jefersonzanim, once completed, reply here with a list of data that should be fixed. 

I guess that the "topic" name, if needed, at the end should be fixed manually

**Comment by jefersonzanim** [comment]
@mmagaldi-eng we've completed all work in the dashboards in a session with end-users. These issues are related to data issues:


- The tweets ingestion should be reactivated, and we should be sure that the hashtags we gave David work properly. Please arrange for a test run this week if possible.

Publisher 

- Country is not working very well…
- Nationality, same as above
- Name is almost always without spaces, not very readable

Claims

- Rating is 0 for 455 claims (we can translate the label value into a figure – we can give you a table reference if you need it)
- Claim: about 10,000 claims have the Claim/Text field empty
- Source is also empty (what value should be there?)
- Author.name is almost never matches the name of the Author and should be corrected or removed (or at least not taken into account)
- mentions contains hexadecimal values. Why?


These are the ones we went through in the call. There could be other problems with data that are not apparent in dashboards.

**Comment by jefersonzanim** [comment]
This is complete from the dashboard perspective. I suggest creating another issue for the remaining data problems.

**Comment by neilpbyrne** [comment]
@jefersonzanim and @vittorianovancini I have made the small changes that arose during our session. Namele:
- If tweet doesn't have country, remove (None), otherwise show country. eg -(ES)
- in Article layout template, click on headline to filter dashboard with this article
- fix color lense on graph. Now shows red for score less than 30, yellow between 30 and 65, and green above 65

I'm still working on the strange graph expansion but will comment here when that's done
