### ISSUE TITLE
Main page: Siren button should be explained or changed

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#12]
Vittoriano: "What Siren offers could make the difference with other platform similar to our own. I suggest to change the mouseover to say “Open Advanced Investigative functions on the Siren Platform” or “Open Siren Investigative Services for the Advanced User”."

Hans from VRT suggested something like this:

<img width="598" alt="Screenshot 2019-07-03 at 16 47 34" src="https://user-images.githubusercontent.com/17741/60601356-49d5d200-9db2-11e9-9eb6-94e316833d10.png">

**Comment by macagari** [comment]
@dcabo it'll be changed as in the picture.
