### ISSUE TITLE
Please Ingest Open Data

### ISSUE THREAD

**Issue by vittorianovancini** [fandangOrg/fandango#120]
There is no Open Data in the system, yet. Please ingest the list you already have so we can see if all works as it is supposed to do. Since next week we start some of the Pilots second phase, it would be good to show all the Fandango functionality at work. Thanks for your help and consideration. I'll be available to help with any more data you need or any problem you encounter with the data quality.

**Comment by pstalidis** [comment]
At the plenary meeting I promised to have open data ingested by 5/3/2021 eod.

**Comment by pstalidis** [comment]
Open data (>15k) are in the database

**Comment by vittorianovancini** [comment]
Thanks. But, please, reactivate the visualization of the Open Data in Fandango basic interface. Are they visible in the Dashboards? And where?

**Comment by mmagaldi-eng** [comment]
I guess this is something that should involve @neilpbyrne, @pstalidis and @macagari

**Comment by pstalidis** [comment]
since data are already ingested, this issue is solved.
I have started a new issue about the visualisation of the data #121
