### ISSUE TITLE
No open data in UI

### ISSUE THREAD

**Issue by pstalidis** [fandangOrg/fandango#121]
even though open data actually exist in fdg-fact index
![the_index](https://user-images.githubusercontent.com/24522654/110783025-87ba1780-8270-11eb-96e4-948446a11df3.png)

the UI shows no open data
![user_interface](https://user-images.githubusercontent.com/24522654/110783018-84bf2700-8270-11eb-9e4a-795afc6946ee.png)

**Comment by macagari** [comment]
I'm trying to call "find facts" service to get open data but I get a "bad request" message. Can you update the file with API https://docs.google.com/spreadsheets/d/15cWJwX9D0XuY7zficapz55AoXkC2NfYDowfLSPZSpwE/edit#gid=1207208562? @neilpbyrne

**Comment by mmagaldi-eng** [comment]
@neilpbyrne during the call, today, has assured that he will fix this service ASAP

**Comment by mmagaldi-eng** [comment]
> I'm trying to call "find facts" service to get open data but I get a "bad request" message. Can you update the file with API https://docs.google.com/spreadsheets/d/15cWJwX9D0XuY7zficapz55AoXkC2NfYDowfLSPZSpwE/edit#gid=1207208562? @neilpbyrne

@neilpbyrne any news about this?

**Comment by neilpbyrne** [comment]
@mmagaldi-eng I have fixed this. I need to redeploy and contact @macagari to make sure the service is being called correctly. I'm on a call at the moment so will do this as soon as I'm free aftterward

**Comment by neilpbyrne** [comment]
@mmagaldi-eng myself and @macagari had a call about this and you will see the correct open data web service results in the UI later today
