### ISSUE TITLE
Main page: progress bar needed

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#13]
Vittoriano: "The spinning wheel is associated to something which is not working like it should for Mac Users, or like the dreaded hourglass for (historic) Windows users. A Progress Bar should be used instead in all the processes on the Fandango platform, especially those associated to photo and video functions, as they could require substantial amount of time."

Hans: "I get the point, but I know how hard a progress bar is to implement. Or it used to be, at least, because you have to know exactly how far along the process is. Which is/used to be difficult. Let's assess the costs and benefits of such an implementation. LiveTech, can you give us some info on that?"

**Comment by pstalidis** [comment]
We can provide (after the review) a very rough estimation on media analysis progress.  
then the UI will have to show it

**Comment by macagari** [comment]
For now it's not a priority, we can talk about this after the review.

**Comment by pstalidis** [comment]
field "progress" returns an estimate of the progress for video analysis (20% for download, 20% for extracting frames, 50% for analysing frames, 10% for creating mp4 video)
progress for image analysis will wait until blob storage #62

**Comment by macagari** [comment]
Oh sorry, Today I forgot to show but it's done, the bar progress is there, on the video service. Let me know if it's ok. :)

**Comment by pstalidis** [comment]
The progress bar looks fine to me

**Comment by pstalidis** [comment]
Progress bar working
