### ISSUE TITLE
Claims: improvements to results page

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#17]
Combination of feedback from different users, sorted roughly by priority:

1. The URL of the original text is missing from the result and it should be there, so users can go there and see additional information.

1. Please include author and evaluation of the Claim Review.

1. Body should be formatted. The current unformatted text, without line breaks, is very difficult to read and a time consuming process.

1. If this is the text extracted from the claim review field, it should say so. I suggest to change “Body” with CLAIM REVIEW TEXT.

1. Date: Can we confirm this is the original publication, not the date we retrieved it? Maybe we should change the label to "publication date". The date is formatted with too much detail (seconds).

1. Duplicates should be avoided. This may have been a temporary issue with dirty data in Elastic, we'll check to see whether it happens again.

**Comment by pstalidis** [comment]
there are multiple issues here both for the front and the back end
i will start answering the back-end ones
1. the url is already stored in the database
2. author and evaluation are stored when available in the schema. 
4. the text returned is the one available in the web page. 
5. the publication date is the date provided in the schema. (if it is missing the oldest known date of being published is used)
6. there is a single entry per unique url and claimReviewed (small text describing claim under review; similar to a page title) found.

**Comment by dcabo** [comment]
@danielevannella is there any progress on this issue? I can't prepare the presentation for the review properly if I can't see the original URL and the review result.

**Comment by pstalidis** [comment]
Closing the issue assuming that it has been solved before the review.
