### ISSUE TITLE
The navigation bar in the results page is confusing

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#18]
Vittoriano: "In the results page of any section (Article, Claim…) clicking on the buttons at the top just changes the URL. It would be better to go to the home page and select the clicked section, for two reasons: now it looks like nothing has happened, which is confusing; after clicking on a button the browser URL is not the one for the results anymore, which leads to mistakes of sharing the wrong URL."

Hans from VRT commented:

> this confusion might be caused by the order of the elements. It now seems like the buttons depend on the search action because they’re below the search box.
> 
> <img width="593" alt="Screenshot 2019-07-04 at 13 09 10" src="https://user-images.githubusercontent.com/17741/60662529-eeace980-9e5c-11e9-86fd-bc8817401f12.png">
>
> (A bit like you refine Google Search results by using the buttons Images, News, Videos.)

And suggested switching the elements upside down, like this:

<img width="591" alt="Screenshot 2019-07-04 at 13 10 17" src="https://user-images.githubusercontent.com/17741/60662591-17cd7a00-9e5d-11e9-9f12-b3b8b475eadb.png">

The buttons would lead to the homepage with the action selected, as Vittoriano suggested.

**Comment by macagari** [comment]
OK, We can fix that, not a problem.

**Comment by pstalidis** [comment]
@macagari if it has been fixed please close the issue

**Comment by dcabo** [comment]
Doesn't apply anymore with new layout
