### ISSUE TITLE
Video: improve handling of links

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#19]
Vittoriano: "the VIDEO service should be able to extract video URLs from web pages, like it does in the ARTICLE page, since it is difficult to find the Video URL on news pages. Also, the VIDEO search does not seem to work with short links, used by many news websites. By the way, Vimeo denied connection to Fandango service when I tried it."

**Comment by pstalidis** [comment]
I will look into this

**Comment by pstalidis** [comment]
We are using the youtube-dl library to download videos.
The list of supported sites can be found [here](https://ytdl-org.github.io/youtube-dl/supportedsites.html). Vimeo is generally supported. 
@dcabo Could this be a **private** video that you tried?
I will add the request for url extraction as a new issue #24.

**Comment by pstalidis** [comment]
Closing this issue. Reopen if the problem continues to exist.
