### ISSUE TITLE
Image manipulation: more information is needed in the results

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#20]
The version we evaluated in June, during the Rome meeting, was not fully completed, and just showed coordinates of bounding box and a general percentage, which we agreed could be misleading.

We all decided to offer more information to the user: making the full mask / heatmap generated by the AI model visible to the user, for example. Or at least drawing the boxes on top of the images, instead of displaying the coordinates.

**Comment by pstalidis** [comment]
the service is now returning the full heatmap generated from the classifiers
the output should be shown to the user interface

**Comment by pstalidis** [comment]
I see that the UI now shows the heatmaps
