### ISSUE TITLE
Article analysis: ignore small pictures

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#21]
I think we could skip the small images below a certain size. Let's say 100 pixels x 100 pixels.

That way icons and logos wouldn't be shown (cleaner to the user), and there would be less work for Fandango to process. In any case, the AI models probably don't work well with such small pictures.

**Comment by pstalidis** [comment]
images smaller than 100x100 pixels and images with ratio (height/width) less than 1/3 or more than 3. are no longer analyzed but return "status": "error", "error": "not supported image shape"
