### ISSUE TITLE
Article analysis: UI improvements

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#22]
Several issues:

- Body: the text should respect the line breaks, otherwise it can't be read. We should discuss whether we want to respect the URLs also.

- There should be a link to the original article.

- The publication date for [an article from The Guardian](https://www.theguardian.com/politics/2019/jul/04/jeremy-hunt-refuses-to-rule-out-sanctions-against-china) is currently missing. The article could be old and ‘reposted’, this has significance for the journalist.  

- There's currently no author and no publisher for [a normal article from The Guardian](https://www.theguardian.com/politics/2019/jul/04/jeremy-hunt-refuses-to-rule-out-sanctions-against-china) so we can't evaluate this part.

- Typo: "Not authors found" should say "No authors found". Same with publishers.

- There's a typo: "similiar news" should say "similar".

**Comment by pstalidis** [comment]
@danielevannella please fix the spelling mistakes (5,6)
@danielevannella the back end provides a url, include it (2)
@danielevannella if this is not already fixed, a suggestion would be to show the summary here and redirect the user to the original (formatted) article using the link (1,2)

**Comment by pstalidis** [comment]
html, the language web pages are written in, is a presentation and formatting language and does not have semantic information included. what a human can clearly see and understand is not necessarily easy for a machine to recognise and attach the necessary semantics to it. that means that while **we** can recognize the date and author, the **crawler** might miss. (3,4)
as we have discussed, if there is a publication date extracted it is used in our processed article. if there is no date (or we couldn't extract it) we use the crawling date (it is the earliest date we **know** that the article **was** published) and note in an additional field that the date was estimated. this leaves the choice to the journalist to take into consideration or not. (3)
i am opening a new issue (#35) about misses in authors and publishers (4)

**Comment by pstalidis** [comment]
@danielevannella when 1,2,5 and 6 are handled please close the issue

**Comment by pstalidis** [comment]
I am assuming these are fixed
