### ISSUE TITLE
Technical Data Quality Analysis

### ISSUE THREAD

**Issue by jefersonzanim** [fandangOrg/fandango#25]
Issue to track all the data quality scenarios that needs to be addressed. I'll make a list as we can strike through them as we finish it. This analysis is based on final data inserted in ES.

Mappings for indices are here: https://github.com/fandangOrg/fandango/blob/elasticsearch-6.x/system/elasticsearch_mappings/create_and_update/

- [ ] fdg-ap-person and fdg-ap-organization field identifier needs to filled with values matching article.author and article.publisher.

**Comment by dmgutierrez** [comment]
Hi Jefferson,

I have included a new 128 character identifier to be used instead of the id that elasticsearch provides you when you create a new document to solve the issue..

**Comment by pstalidis** [comment]
@jefersonzanim 

can you update "fdg-topic" to include "identifier", "name" and "keywords" fields. they are all "text"/"keyword" type.

something like:
{
    "index_patterns" : "fdg-topic",
    "mappings" : {
      "doc" : {
        "properties": {
            "identifier":{
                "type":"text",
                "fields": {
                    "keyword": {
                        "type": "keyword",
                        "ignore_above": 10000
                    }
                }
            },
            "name":{
                "type":"text",
                "fields": {
                    "keyword": {
                        "type": "keyword",
                        "ignore_above": 10000
                    }
                }
            },
            "keywords":{
                "type":"text",
                "fields": {
                    "keyword": {
                        "type": "keyword",
                        "ignore_above": 10000
                    }
                }
            },
        }
        }
    }
}
should work

**Comment by pstalidis** [comment]
I can only assume that this has been fixed.
If the problem persists you can re-open the issue
