### ISSUE TITLE
Cookie policy is presented as Title & Body in Article analysis dashboard

### ISSUE THREAD

**Issue by ilkelemmelijn** [fandangOrg/fandango#29]
This is the case for all articles on www.hln.be for example

**Comment by pstalidis** [comment]
I am going to perform some tests with a new extraction library and see if cookie policy etc are handled better

**Comment by macagari** [comment]
Well, I think this is something to handle with the preprocessing, don't you ?

**Comment by pstalidis** [comment]
@macagari No, unfortunately this has to do with how the crawlers work.

**Comment by pstalidis** [comment]
Unfortunately the new extraction library did not fix this issue
