### ISSUE TITLE
Facebook crawler

### ISSUE THREAD

**Issue by danielevannella** [fandangOrg/fandango#3]
Hi guy I find in kafka  sources as  Facebook, reddit, twitter, and others. My questions are: 

1) Are they old data in Kafka?
If yes, I ask @giocalor   to clean all the old queues.

**Comment by giocalor** [comment]
Kafka data has 6-7 days retention time, so we should investigate about it. 
Not sure if @pstalidis needs a data example to check.

**Comment by pstalidis** [comment]
There **should not** be any data from sources other than the ones provided from the end-users.
During the services testing **old data** were inserted to the kafka queues.
@giocalor can you please remove **all** data in kafka to be on the safe side?
