### ISSUE TITLE
Edit fields in the kafka queue

### ISSUE THREAD

**Issue by pstalidis** [fandangOrg/fandango#34]
following from @jefersonzanim comment in #28 
> The about field on the Article should contain something like: ["potato","land","rain","plague"]
> Then, we need a new field on the Article that will be "topic". This new field will contain: ["Agriculture"]
we need to add a field called "topic" in the aggregated article.

**Comment by pstalidis** [comment]
@danielevannella the topics service (both offline and online) now returns an additional field called "topic" of type text which should be included in the Article.
@AlbertoGhedin who do i assign this to for eng?

**Comment by AlbertoGhedin** [comment]
To Massimo. In all the cases Federico is on it

**Comment by pstalidis** [comment]
@AlbertoGhedin I can't find Federico's handle, can you assign it to him?

**Comment by federicovagnoni** [comment]
Hi @pstalidis! I've added the topic field in the final article. Just to be clear: is it a string or an array of strings? P.S.: now you can tag me in the issues!

**Comment by pstalidis** [comment]
It is a string.
ps: great :)

**Comment by danielevannella** [comment]
Hi @pstalidis , now I receive this json:

about
mentions
identifier 

Is it Correct?

**Comment by pstalidis** [comment]
you should be getting:
```
            {
                "identifier": article,
                "about": keywords,
                "topic": topic,
                "mentions": entities
            }
```
don't you get topic?

**Comment by danielevannella** [comment]
{'about': ['altro', 'italiano', 'potere', 'sempre', 'parlare', 'provincia',
'stare', 'partire', 'societa', 'richiedere', 'politico', 'consigliare',
'tempo', 'presidente', 'andare', 'locale', 'problema', 'vero', 'camera',
'cosa', 'cercare', 'mese', 'bastare', 'modo', 'bene', 'diritto', 'cosi',
'spesa', 'chiamare', 'giovane', 'certo', 'usare', 'dirigere', 'nuovo',
'dire', 'chiudere', 'contare', 'grande', 'arrivare', 'allora', 'mai',
'bisognare', 'territorio', 'porto', 'nazionale', 'persona', 'provare',
'fare', 'solere', 'vita', 'puo', 'ancorare', 'cittadino', 'ricevere',
'utilizzare', 'causare', 'corto', 'civile', 'decidere', 'riuscire',
'parere', 'spiegare', 'qui', 'primo', 'italia', 'pubblicare', 'restare',
'molto', 'denunciare', 'esempio', 'medico', 'leggere', 'anno', 'sicurezza',
'orare', 'poi', 'invece', 'essere', 'via', 'menare', 'casa', 'rendere',
'giorno', 'marcare', 'comune', 'pensare', 'sindacare', 'perche', 'ex',
'volto', 'avere', 'fonte', 'caso', 'gia', 'condurre'], 'identifi
er':
'5e9b12b2f0d378b424a5461c516aabc24ab4efc4d630340ee6bdbbaa54dfa132ff552ec7b4b6ec8cee9d0cdbeda886c8f31bd10d6cb3ae35bca7c84324d41783',
'mentions': ['c17d7014b2adfdd4e7272d161f70f3c4',
'b43ec1262592412716b9c036944e56c2', '84392a689b19b245779f7b85c81c215b',
'77dcfc4d54ab79daa888db100d0cd508', '0a2c5d954e991fc7227caf023cf472be',
'3727a0db3c098c602819f0cfd58e9830', '6f329a761c9b1507c400f2831f5218d1',
'a092550a107cb26815e7c3730719f14f', '4d0cce9e32bae3a125fd4fa090fccc3c',
'264befcae2cf16d0dbb4e26d442bdb7b', '5268aab7e78237b7b68a812d54a7c89b',
'3245c33da9ed762e62917622c5cb3e84', '6124bb5cc771b2c233450d654ba75c56',
'1add8e8adfa5e4be01ef72333549bfab', 'e4fb2e87bbbe4b1e8a3174c364c792f7',
'708d1cb1f8bf5a4b3988e776975ac418', '6562f3ef8922ebab2724e63af47e4496',
'f007159b0594d899a41ff1220880f065', '3748b43fb7e35ed6031f5ab9d8dab5b5',
'0a92e98275cc600f951961180a53a38c', '1dc56d741889a57c4041fde319efc0c4',
'7f1f8da4023b5d9f397d9e0c983247ea', '8351b03a27eae1823eeaf6c60c2bb942',
'134f55c9cb7855b13ddc6
b96d6696907']}

this is json

Il giorno lun 22 lug 2019 alle ore 14:35 Panagiotis Stalidis <
notifications@github.com> ha scritto:

**Comment by pstalidis** [comment]
now?

**Comment by danielevannella** [comment]
No,

is it correct this url http://40.114.234.51:5006?

Il giorno lun 22 lug 2019 alle ore 15:19 Panagiotis Stalidis <
notifications@github.com> ha scritto:

**Comment by pstalidis** [comment]
Ok, found the problem, i was updating the wrong file.
It should be ok now.

**Comment by pstalidis** [comment]
@danielevannella can I get a reply if everything is ok?

**Comment by danielevannella** [comment]
Good :D

{'about': ['altro', 'italiano', 'potere', 'sempre', 'parlare', 'stare',
'partire', 'societa', 'richiedere', 'fondamento', 'consigliare', 'tempo',
'andare', 'problema', 'vero', 'municipio', 'cosa', 'cercare', 'mese',
'bastare', 'chiesa', 'modo', 'bene', 'entrare', 'municipale', 'gennaio',
'cosi', 'chiamare', 'giovane', 'certo', 'usare', 'dirigere', 'nuovo',
'dire', 'contare', 'grande', 'arrivare', 'allora', 'mai', 'bisognare',
'castello', 'porto', 'persona', 'provare', 'fare', 'solere', 'vita',
'falso', 'citta', 'puo', 'fuoco', 'ancorare', 'ricevere', 'quartiere',
'utilizzare', 'causare', 'ieri', 'riuscire', 'parere', 'spiegare', 'qui',
'primo', 'italia', 'pubblicare', 'restare', 'molto', 'denunciare',
'esempio', 'leggere', 'anno', 'orare', 'poi', 'censurare', 'invece',
'palazzo', 'essere', 'via', 'intervenuto', 'casa', 'rendere', 'menare',
'giorno', 'pensare', 'sera', 'perche', 'evacuare', 'ex', 'volto', 'avere',
'firmare', 'tribunale', 'fonte', 'caso', 'gia'], 'identifier': '92ce19eea
1e0b639b790e1cf359c90acb8e0c30a999e73f59396c868b8a7bbb0036475d968644fdd7b514eb49940c6e8d10c4539024f9f40a499bcdad6a3f118',
'mentions': ['ed39692361ffd0cdb01d32b8c1c07544',
'e4f18617c152a134c7238992a11cbaf1', '47c1b9baca7ba46eca6a7a13a19e1f44',
'7bd1b012daca76ae70982798b519bbfd', '6bbb53a54d8b14c81cc56f8988f84fbc',
'eee474622b94b792709cb2e03234d984', 'e00585565bfe8a60b430a185ec9bce1c',
'1ac569905d70d19bf3e879b91e3136bc', '6a489442e0b567f7ed822a7bc726f12b'],
'topic': '?'}

thanks... only one question... Why I'm receiving tihs "?" ?



Il giorno mar 23 lug 2019 alle ore 10:56 Panagiotis Stalidis <
notifications@github.com> ha scritto:

**Comment by pstalidis** [comment]
because that is the label defined by the end users.
I am now closing this issue
