### ISSUE TITLE
missing author and publisher in article

### ISSUE THREAD

**Issue by pstalidis** [fandangOrg/fandango#35]
There's currently no author and no publisher for a [normal article from The Guardian](https://www.theguardian.com/politics/2019/jul/04/jeremy-hunt-refuses-to-rule-out-sanctions-against-china) so we can't evaluate this part.

**Comment by pstalidis** [comment]
just tested and the author is parsed correctly by the crawler.
I am closing this issue for now
If we can find other examples please reopen

**Comment by neilpbyrne** [comment]
Just noticed a similar issue recently when entering an article url to the system. 

It seems this article has author: https://www.repubblica.it/cronaca/2020/12/04/news/caso_suarez_sospesi_i_vertici_dell_universita_per_stranieri_di_perugia_i_pm_la_juventus_si_e_attivata_per_accelerare_la_-276978725/?ref=RHTP-BH-I274300569-P1-S1-T1

But the system did not see it:
![no_author](https://user-images.githubusercontent.com/45828285/101652048-aa505080-3a35-11eb-8935-c1996b05da8b.PNG)
