### ISSUE TITLE
Similar Articles not showing when Article first analyzed

### ISSUE THREAD

**Issue by neilpbyrne** [fandangOrg/fandango#36]
When I analyze an article through the UI, I see "No similar Articles" upon first analysis.
If I reload the page the similar articles show. 

My guess is that the FinsSimilarArticles endpoint is being called *before* the analysis returns an article id.

**First Load**
![just_loaded](https://user-images.githubusercontent.com/45828285/61545914-6cb5e680-aa40-11e9-8727-16e8a6669d82.png)

**Page Reloaded**
![reloaded](https://user-images.githubusercontent.com/45828285/61545950-7a6b6c00-aa40-11e9-94dd-8676050b8308.png)

**Comment by neilpbyrne** [comment]
@macagari can you see this?

**Comment by macagari** [comment]
@neilpbyrne yep!

**Comment by macagari** [comment]
I think that's the problem, thank you :) @neilpbyrne

**Comment by neilpbyrne** [comment]
@macagari ahhh there you are :)

**Comment by macagari** [comment]
Come on ! now I have to work xD @neilpbyrne

**Comment by neilpbyrne** [comment]
Hey @macagari , looks like this is fixed. Nice work! Will I close this issue?
