### ISSUE TITLE
extract_topics services error

### ISSUE THREAD

**Issue by danielevannella** [fandangOrg/fandango#39]
Hi guy, we have this problem:

SERVICE TOPIC 500 Server Error: INTERNAL SERVER ERROR

http://40.114.234.51:5006/api/extract_topics

@theosem @pstalidis

**Comment by danielevannella** [comment]
Sorry, I'have again this error. 

ERROR SERVICE TOPIC 500 Server Error: INTERNAL SERVER ERROR for url: http://40.114.234.51:5006/api/extract_topics

please Help me :D 

@pstalidis

**Comment by AlbertoGhedin** [comment]
Please Assign to assignee in order to help colleagues to address the issue

**Comment by pstalidis** [comment]
we had a power failure, the service is back up.
@danielevannella if a service is down please send an email instead of adding an issue

**Comment by danielevannella** [comment]
Hi guys,

we update new docker image. 

best
DV
