### ISSUE TITLE
Kafka Manager

### ISSUE THREAD

**Issue by danielevannella** [fandangOrg/fandango#4]
Hi @giocalor , please could you give as a monitor interface of kafka  to check the status of each queue?

**Comment by federicovagnoni** [comment]
Hi Daniele, you can find the monitor interface at http://40.114.234.51:9001/kafkahq
You can find the Usage Guidelines here: https://docs.google.com/document/d/1jrJKR-lvhAY1n5N2_Wps8FcBwKoTIejr17Mat8iq520/edit?usp=sharing
