### ISSUE TITLE
certh_offline_ner_service crashed

### ISSUE THREAD

**Issue by federicovagnoni** [fandangOrg/fandango#42]
Hi!
The service worked well all night long, but 2 hours ago it crashed with this error:

![immagine](https://user-images.githubusercontent.com/4192579/61854883-50da9680-aebf-11e9-9511-0a15379c4e2a.png)

I already stopped the crawler.

**Comment by pstalidis** [comment]
fixed

**Comment by federicovagnoni** [comment]
A new error (4 hours ago):
![immagine](https://user-images.githubusercontent.com/4192579/61933014-1a674f00-af85-11e9-8fde-d68b8b9690e0.png)
