### ISSUE TITLE
Text analysis service is stuck

### ISSUE THREAD

**Issue by federicovagnoni** [fandangOrg/fandango#44]
![immagine](https://user-images.githubusercontent.com/4192579/62042857-59a0d480-b1ff-11e9-978f-2312ff56fabf.png)

**Comment by macagari** [comment]
@federicovagnoni We will check as soon as possible, thanks for letting us know

**Comment by federicovagnoni** [comment]
Hi guys!
I don't know if you had time to check it (I think the image has been updated), but the error is still there!
