### ISSUE TITLE
Wrong layout of navigation buttons on narrow widths

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#46]
The buttons in the navigation bar get wrapped up when the browser width is not enough. This is a very weird behaviour. Also because the full width is not being used. Here you can see how the Siren button falls to a second line:

<img width="1108" alt="Screenshot 2019-07-31 at 12 42 51" src="https://user-images.githubusercontent.com/17741/62205899-d1eacf80-b390-11e9-8404-e56993eb8482.png">

**Comment by pstalidis** [comment]
This has not been fixed yet.

**Comment by dcabo** [comment]
Not applicable with new layout 👍
