### ISSUE TITLE
The logo in the navigation bar gets distorted on certain browser widths

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#47]
The behaviour of the logo in the navigation bar of the results page is not correct.

First, it gets bigger and smaller depending on the browser width, which is a very unusual behaviour. In a normal responsive design, it should stay the same size until the window is too narrow, and then the layout should change  so it moves to be on its own line, not left of the search bar.

Even worse, when it changes size the dimensions are not respected, so we get this, where the logo has been deformed:

<img width="496" alt="Screenshot 2019-07-31 at 12 50 55" src="https://user-images.githubusercontent.com/17741/62206333-dcf22f80-b391-11e9-986a-763bcb861f1c.png">

**Comment by macagari** [comment]
We will fix it.

**Comment by pstalidis** [comment]
logo behavior looks correct.
