### ISSUE TITLE
Claims: duplicated results

### ISSUE THREAD

**Issue by dcabo** [fandangOrg/fandango#48]
We had mentioned in other issues (see #17) that some users had seen duplicated results in the Claim section, but we hadn't been able to reproduce it so far. I just found an example: [this query](http://fandango.livetech.site:15003/analyze/claim;url=immigrazione), which searches for "immigrazione" in the claim database, returns a number of duplicated results from Pagella Politica.

<img width="819" alt="Screenshot 2019-07-31 at 16 13 09" src="https://user-images.githubusercontent.com/17741/62219177-1e90d380-b3ae-11e9-9534-b32b3d86cef6.png">

**Comment by danielevannella** [comment]
@pstalidis @jefersonzanim

**Comment by neilpbyrne** [comment]
I've noticed this too for "Articles" as well as "Claims". I ran a number of queries directly against Elasticsearch and have seen a lot of duplication - sometimes 5+ of the same article, but with different _id

@pstalidis Could you have a look at this, as it must be happening at ingestion?

Thanks

**Comment by pstalidis** [comment]
so, if the id is different, then the url is also different since the id is a hash of the url
i did a search against the url of the example that david sent and i only got a single response

@neilpbyrne can you also check the urls of the duplicate results?

**Comment by neilpbyrne** [comment]
Hi @pstalidis , you are actually correct, the duplicate articles had different ids, which of course means they are from different urls. 
Does it make sense that it's ok to have the exact same article as long as the url is different?

Here are the urls of the fdg-article duplicates (There are actually more than posted below):

https://www.ansa.it/nuova_europa/it/notizie/rubriche/infrastrutture/2019/06/20/germaniaannunciati-scioperi-di-assistenti-di-volo-lufthansa_84a2add1-5f70-48d2-b339-d5c6a7aa2f46.html

https://www.ansa.it/nuova_europa/it/notizie/rubriche/infrastrutture/2019/06/22/mosca-stop-a-voli-delle-compagnie-georgiane-verso-la-russia_b1702cc6-de36-41ad-af28-2de86425b4c2.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/grecia/2019/07/10/turchia-contro-ue-grecia-trivellazioni-a-cipro-legittime_4dd95715-13c5-4285-b3ef-5a89bec1c78d.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/croazia/2019/07/09/croazia-media-13-mld-euro-per-infrastrutture-ferroviarie_d0ea38b7-558a-48bb-a83d-b9b636d5e882.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/bosnia/2019/07/01/balcani-da-oggi-taglio-a-costi-di-roaming-nella-regione_11be9b0c-3547-46d6-8ba1-d9b9737dd2c0.html

https://www.ansa.it/nuova_europa/it/notizie/rubriche/politica/2019/07/22/ucraina-zelensky-verso-la-maggioranza_514fe45c-8aa3-4b7b-aabc-6111bdda3a59.html

https://www.ansa.it/nuova_europa/it/notizie/rubriche/politica/2019/07/22/kosovo-media-messaggio-urgente-di-putin-a-vucic_1fd96f7a-f278-4d33-838c-9c105ae95b6a.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/ungheria/2019/06/27/giro-svelate-le-tappe-ungheresi-apre-la-crono-a-budapest_3f61f38a-d6e7-4e07-9003-46b07e967bc6.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/ungheria/2019/07/02/borissov-italia-e-visegrad-per-georgieva-a-commissione_51b9ecb7-aa73-4ebf-aead-0e5c98302cba.html

**Comment by neilpbyrne** [comment]
Hi @pstalidis , you are actually correct, the duplicate articles have different ids, which of course means they are from different urls.

The strange thing is, even though each of these urls links to a different article, each “articleBody” field in elastic is being populated identically - with the string "For the moment, let us be happy of ‘string theory’". 

Any ideas why that might be??


Here are the urls of the fdg-article articleBody duplicates (There are actually more than posted below):

https://www.ansa.it/nuova_europa/it/notizie/rubriche/infrastrutture/2019/06/20/germaniaannunciati-scioperi-di-assistenti-di-volo-lufthansa_84a2add1-5f70-48d2-b339-d5c6a7aa2f46.html

https://www.ansa.it/nuova_europa/it/notizie/rubriche/infrastrutture/2019/06/22/mosca-stop-a-voli-delle-compagnie-georgiane-verso-la-russia_b1702cc6-de36-41ad-af28-2de86425b4c2.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/grecia/2019/07/10/turchia-contro-ue-grecia-trivellazioni-a-cipro-legittime_4dd95715-13c5-4285-b3ef-5a89bec1c78d.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/croazia/2019/07/09/croazia-media-13-mld-euro-per-infrastrutture-ferroviarie_d0ea38b7-558a-48bb-a83d-b9b636d5e882.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/bosnia/2019/07/01/balcani-da-oggi-taglio-a-costi-di-roaming-nella-regione_11be9b0c-3547-46d6-8ba1-d9b9737dd2c0.html

https://www.ansa.it/nuova_europa/it/notizie/rubriche/politica/2019/07/22/ucraina-zelensky-verso-la-maggioranza_514fe45c-8aa3-4b7b-aabc-6111bdda3a59.html

https://www.ansa.it/nuova_europa/it/notizie/rubriche/politica/2019/07/22/kosovo-media-messaggio-urgente-di-putin-a-vucic_1fd96f7a-f278-4d33-838c-9c105ae95b6a.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/ungheria/2019/06/27/giro-svelate-le-tappe-ungheresi-apre-la-crono-a-budapest_3f61f38a-d6e7-4e07-9003-46b07e967bc6.html

https://www.ansa.it/nuova_europa/it/notizie/nazioni/ungheria/2019/07/02/borissov-italia-e-visegrad-per-georgieva-a-commissione_51b9ecb7-aa73-4ebf-aead-0e5c98302cba.html

**Comment by neilpbyrne** [comment]
@dcabo I just had a look at the duplicate results you pointed out and I see what's happening. 

The domain in question - pagellapolitica.it - publishes articles to www.pagellapolitica.it, and pagellapolitica.it

The urls for both articles are: 
*https://pagellapolitica.it/dichiarazioni/5530/immigrazione-110220-mila-irregolari-in-italia*
*https://www.pagellapolitica.it/dichiarazioni/5530/immigrazione-110220-mila-irregolari-in-italia*

It's the exact same article but as the url is different, it is correctly (technically) seen as a different id and not a duplicate. This could cause a problem as I'm sure plenty of other sites will have replication across subdomains

**Comment by jefersonzanim** [comment]
@Panagiotis Stalidis <stalidis@iti.gr> @Theodoros Semertzidis
<theosem@iti.gr> is this something that can be treated in the crawling to
avoid www duplicating content?

Thanks,
Jeferson Zanim
Head of Client Services, Siren
A Block C, 77 Sir John Rogerson's Quay, Dublin, D02 T804, Ireland
P +353 (0)1 553 0200  <+353+(0)1+553+0200>
M +353 85 107 7810  <+353+85+107+7810>
E jeferson.zanim@siren.io  <jeferson.zanim@siren.io>
W www.siren.io
<http://www.siren.io?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://twitter.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.youtube.com/channel/UCKGsC-vD28r7hW6T9QspKPA?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://vimeo.com/sirenio?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.facebook.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/company/11117365?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by jefersonzanim** [comment]
Tagging @theosem and @pstalidis here to see if they can treat the data collection to prevent collecting duplicated records.

**Comment by pstalidis** [comment]
I will try to think of something and get back to you

**Comment by pstalidis** [comment]
![Screenshot_2019-08-11_10-27-20](https://user-images.githubusercontent.com/24522654/62831130-f5c8d380-bc22-11e9-9c81-e4db66457626.png)
So, one problem is that the crawler incorrectly identifies the circled part as the only text. I added a new issue #61 for this.
The second problem is duplicate articles in subdomains. The only idea I could come up with, that does not require changing the identifiers, is to check both urls (with and without www) and insert only one of them to kafka.

**Comment by jefersonzanim** [comment]
@pstalidis if you consider only the root domain, like 'newsagency.com' and the title, in a way that for each domain you would only have one news article with each title, would that work?

**Comment by pstalidis** [comment]
I have updated the identifier to consist of the root domain (without www) and the path in crawlers version v1.1.1
