### ISSUE TITLE
[First Pilot] Consolidate the Pilot results for the final report 

### ISSUE THREAD

**Issue by jefersonzanim** [fandangOrg/fandango#55]
Depends on https://github.com/fandangOrg/fandango/issues/51 and https://github.com/fandangOrg/fandango/issues/54

Consolidate, create graph visualizations from the data gathered by users on the pilot executions and provide descriptive analysis of the results, culminating on deliverable D6.2.

**Comment by dcabo** [comment]
Pilot 1 is completed and D6.2 delivered.
