### ISSUE TITLE
Blob storage

### ISSUE THREAD

**Issue by pstalidis** [fandangOrg/fandango#62]
Since the output of the media analysis is now image masks and videos and we should store the analysis in the system, we should use some king of blob storage.

**Comment by federicovagnoni** [comment]
Hi Panagiotis!
Here are the guidelines: https://drive.google.com/open?id=1sN52aBMSxWWtvrehVrCtQse16Vpd9ITG-QEQzfw3RpI
You can also find them in the Fandango Project folder.
For the API Key you have to contact me via email.

**Comment by pstalidis** [comment]
Working great! I already changed the video analysis code to use it.

**Comment by AlbertoGhedin** [comment]
Great! We integratred it after july meeting but the documentation was missing..
You see? You ask and you get!!!
