### ISSUE TITLE
Asynchronous data ingestion

### ISSUE THREAD

**Issue by pstalidis** [fandangOrg/fandango#69]
Right now, data ingestion is a synchronous process. This means that **all** analysis must finish **before** an article can be ingested in the database. This means that ingestion can fail if **any** analyser fails (single pint of failure) and the speed of ingestion is limited to the slowest of the analysers. 
Since each part of the analysis is stored separately (fdg-entity, fdg-media, fdg-author, etc), each of the analysers should return a promise (the id in the appropriate index) of where the analysis will be stored and perform the actual analysis in a separate thread.
There are 2 problems (that I can think of) that need to be solved for this:
1. the text modality has to be separated from the article entity (to be consistent with other modalities)
2. we need a notification system for the process that produces an article score that all modalities have been analysed

**Comment by jefersonzanim** [comment]
Hi @pstalidis ! Is there anything I can help directly with this?

**Comment by danielevannella** [comment]
Hello @pstalidis why did you assign me this?

**Comment by danielevannella** [comment]
Sorry I didn't see all.

**Comment by pstalidis** [comment]
@danielevannella I assigned everyone involved in the data ingestion process
@jefersonzanim we should discuss this issue in the next technical call

**Comment by AlbertoGhedin** [comment]
Agree, let discuss in next call

**Comment by dmgutierrez** [comment]
Hi Guys,

The next technical call is planned to be held *this Friday October 4th *or
is the one that we have every two weeks on Tuesdays?

**Comment by jefersonzanim** [comment]
We have a call on Friday. All topics pertinent to the execution of the
Pilots can be addressed then.

Jeferson Zanim
Head of Client Services, Siren
A Block C, 77 Sir John Rogerson's Quay, Dublin, D02 T804, Ireland
P +353 (0)1 553 0200  <+353+(0)1+553+0200>
M +353 85 107 7810  <+353+85+107+7810>
E jeferson.zanim@siren.io  <jeferson.zanim@siren.io>
W www.siren.io
<http://www.siren.io?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://twitter.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.youtube.com/channel/UCKGsC-vD28r7hW6T9QspKPA?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://vimeo.com/sirenio?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.facebook.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.linkedin.com/company/11117365?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by mmagaldi-eng** [comment]
I'm sorry guys, but I cannot attend the conf call tomorrow. 
We should discuss about it next week (I've just sent an email on this). 
As I've written, to reduce reworking we should consider this together with fusion score (T4.5).

**Comment by mmagaldi-eng** [comment]
> @danielevannella I assigned everyone involved in the data ingestion process
> @jefersonzanim we should discuss this issue in the next technical call

@pstalidis don't forget that (despite myself) I'm the person in charge of the "offline" process... ;)

**Comment by jefersonzanim** [comment]
@mmagaldi-eng there's no technical call currently scheduled.

**Comment by pstalidis** [comment]
@mmagaldi-eng sorry, I thought I had assigned you too
@jefersonzanim FANDANGO - Technical Call
Tue, Oct 8, 2019 10:30 PM - 12:30 AM CEST
Please join my meeting from your computer, tablet or smartphone.
https://global.gotomeeting.com/join/990869773

**Comment by danielevannella** [comment]
I'll be at a conference.


Il giorno ven 4 ott 2019 alle ore 15:36 Panagiotis Stalidis <
notifications@github.com> ha scritto:

**Comment by pstalidis** [comment]
ingestion has been postponed for after the pilot execution

**Comment by pstalidis** [comment]
This should have been closed a long time ago
