### ISSUE TITLE
The scores for authors are getting to 50 all time

### ISSUE THREAD

**Issue by tavitto16** [fandangOrg/fandango#70]
By some how, periodically, the values that an author has are settled to 50 that is the initial value. Fortunately, we have a backup in the Neo4j DB, however, we need to understand why is this happening to inserted to ES and solve it

**Comment by tavitto16** [comment]
UPM will check the overall workflow, we have an intuition...  We will update it early next week. BR

**Comment by vittorianovancini** [comment]
Maybe, instead of 50, an author not scored before could start with a N/A by default?

**Comment by mmagaldi-eng** [comment]
UPM, did you find a solution to this issue?

**Comment by dmgutierrez** [comment]
We updated the version after the Madrid meeting to correct this issue but we have not tested in a real scenario since the ingestion was stopped.
