### ISSUE TITLE
Services down

### ISSUE THREAD

**Issue by danielevannella** [fandangOrg/fandango#73]
Hy guys, all services are down.

**Comment by federicovagnoni** [comment]
Hi @danielevannella! The disk is at 99% of usage. Can you guys cleanup all the docker containers and images that you don't need anymore? Thank you! @pstalidis @dmgutierrez

**Comment by danielevannella** [comment]
removed

**Comment by federicovagnoni** [comment]
Hi @pstalidis @dmgutierrez! Any news?

> 
> 
> Hi @danielevannella! The disk is at 99% of usage. Can you guys cleanup all the docker containers and images that you don't need anymore? Thank you! @pstalidis @dmgutierrez

**Comment by dmgutierrez** [comment]
Hi guys,

I'm going to ask Gustavo to check whether we need to cleanup old versions
of the docker containers.

**Comment by pstalidis** [comment]
Sorry, I was at at workshop today. Cleaned up old images and containers.
I started the online service.
