### ISSUE TITLE
Extract topics service

### ISSUE THREAD

**Issue by macagari** [fandangOrg/fandango#85]
As I reported weeks ago, the service continues returning the following error message: 

 MaxRetryError: HTTPConnectionPool(host='localhost', port=5006): Max retries exceeded with url: /api/extract_topics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f42fd91e860>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by pstalidis** [comment]
This curl command is working: 
curl -X POST -H "Content-Type: application/json" http://fcerthonline.westeurope.cloudapp.azure.com:5006/api/extract_topics -d '{"data": {"articleBody": "this is a testing text to check if topics are working", "language": "en", "identifier": "online"}, "status": 200, "message": "OK"}'
and so is this:
curl -X POST -H "Content-Type: application/json" http://fcerthonline.westeurope.cloudapp.azure.com:5006/api/extract_topics -d '{"articleBody": "this is a testing text to check if topics are working", "language": "en"}'

both are returning:
{"data":{"about":["former","keep","thing","many","year","work","long","would","leave","often","also","hand","red","be","change","white","old","think","want","say","add","way","dress","black","new","day","even","do","need","claim","little","share","expert","week","last","much","make","believe","may","take","get","look","reveal","mother","night","good","time","really","could","pair","people","report","can","call","s","tell","appear","picture","come","wear","feel","see","star","turn","problem","level","give","not","find","create","have","show","go","system","month","help","use","include","know"],"identifier":"online","mentions":[],"topic":"Fashion"},"message":"Successful Operation","status":200}

Please verify that you are calling the correct service (http://fcerthonline.westeurope.cloudapp.azure.com:5006/api/extract_topics) and that you are sending the correct content ('{"articleBody": "this is a testing text to check if topics are working", "language": "en"})
