### ISSUE TITLE
Services Down

### ISSUE THREAD

**Issue by danielevannella** [fandangOrg/fandango#9]
Hi guys,

preprocessing is down.

docker ps:

CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                    NAMES
28b74a591f7a        livetech/fandango-fake-news:0.2.4 
6bd5be8e0c98        certh_offline_media_service

**Comment by AlbertoGhedin** [comment]
The process is down because because UPM is working on it

**Comment by AlbertoGhedin** [comment]
Reassigned to David

**Comment by pstalidis** [comment]
this is not an issue
