### ISSUE TITLE
Forward of field "keywords"

### ISSUE THREAD

**Issue by pstalidis** [fandangOrg/fandango#90]
In order to improve the quality of topic keywords (#86), we should also consider the keywords extracted by the crawlers.
These exist in the "keywords" field of the raw_article.

Preprocessing is ignoring this field but now we need this forwarded to the analysers.

@dmgutierrez please edit the preprocessor to forward this field.
@macagari this will affect also the output that you get in the online process.

**Comment by dmgutierrez** [comment]
I'm working on it. I will include a new version of the preprocessing on Monday with the keywords fields on it.

**Comment by dmgutierrez** [comment]
@pstalidis @mmagaldi-eng @macagari  I have updated the preprocessing to have the keywords. Once we test it, I will close the issue.
