### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by antoniofelipecora** [fandangOrg/fandango#92]
I'm trying to access Fandango since yesterday, but it seems to be down.
Both the front end at http://52.157.105.38:9800/web/article or the Siren at http://40.114.234.51:8080/ are not working.

@AlbertoGhedin and\or @mmagaldi-eng, could you please check that?

**Comment by pstalidis** [comment]
@antoniofelipecora The platform is only working during business hours CET (i.e. 10:00 to 18:00 CET)
